paths: {
    data_src: "/kaggle/input/rsna-breast-cancer-detection/test_images/",
    data_dest: "/kaggle/temp/preprocessed/mammosub224.h5",
    metadata_src: "/kaggle/input/rsna-breast-cancer-detection/test.csv",
    metadata_dest: "/kaggle/temp/preprocessed/metasub.json",
    data_ids_dest: "/kaggle/temp/preprocessed/submission_split.json",
    model_load_src: "/kaggle/input/rsna-breast-cancer-model-weights/20230225/densenet_ckpt_01.pth",
    submission_path: "/kaggle/working/submission.csv"
}

preprocess_params: {
    file_extension: "h5",
    init_downsample_ratio: 2.5,
    resolution: [224, 224],
    normalization: True,
    test_set: True,
    num_samples: null,
    test_size: null
}

metadata_params: {
    test_set: True,
    selected_columns: ['image_id', 'patient_id', 'laterality', 'view'],
    laterality_map: {'L': 0, 'R': 1},
    view_map: {'CC': 0, 'MLO': 1}
}

dataset_params: {
    augmentations: ["contrast_brightness", "flip", "rotate", "noise"],
    labels: ["patient_id", "laterality", "view"] 
}

model_params: {
    in_chans: 1,
    num_classes: 4,
    pretrained: False,
    drop_rate: 0.5,
}

run_params: {
    train: False,
    disable_cuda: False,
    model: "resnet18",
    batch_size: 1,
    loss_weights: [0.3, 0.7],
    label_weights: [0.75, 0.14, 0.07, 0.04],
    laterality_map: {0: 'L', 1: 'R'},
    view_map: {0: 'CC', 1: 'MLO'},
}
